apiVersion: v1
kind: Secret
metadata:
  name: nexus-secrets
  labels:
    app: nexus-bot
type: Opaque
data:
  # Substitua pelo valor da sua chave OpenAI em base64
  OPENAI_API_KEY: c2stcHJvai1rY295V0RCY2I5bUk1eEUwWDhVYVpYenlYbTAwVWgwZTJWbXlYT3VuNXJaT3EydjRMa2hkcGlPWmZLeTZadEtIeG9BaWFsZG1tRlQzQmxia0ZKYWNmZl9Od19FQ0ZaOHE3bUE0U3NXeGs1aTFkdEhyZGNPYjFWb3dkS0tILUNiNXJ2NHh5a3JhRjRsWTgweTdvZGN1cEpuTk94a0E=